version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - localstack
      - redis
    command: >
      sh -c "until curl -s http://localstack:4566/_localstack/health | grep '\"s3\": \"available\"'; do sleep 2; done && python3 /app/setup_localstack.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # LocalStack's main endpoint for all services
    environment:
      - SERVICES=s3,dynamodb  # Activate S3 and DynamoDB services
      - DEBUG=1
      - DATA_DIR=/localstack_data  # Use a project directory for persistence
    volumes:
      - "./localstack_data:/localstack_data"  # Store data locally in the project directory
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4566/_localstack/health | grep '\"s3\": \"available\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # Add a start period to give LocalStack more time to initialize

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5